# Generated by Django 5.2.13 on 2026-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_kudos_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
