# Generated by Django 5.2.13 on 2026-04-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_achievement_alter_habitreminder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_public',
        ),
    ]
